spring.application.name=order-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3316/order_service
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# url inventory service
inventory.service.url=http://localhost:8082